name: Tests

on: [push]

jobs:
  unit:
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check out github repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: "Create env file"
        run: |
          touch .env
          echo MAINNET_RPC="${{ secrets.MAINNET_RPC }}" >> .env
          echo GOERLI_RPC="${{ secrets.GOERLI_RPC }}" >> .env
          cat .env

      - name: Build smock
        run: yarn build

      - name: Run smock for test contracts
        run: yarn smock-test

      - name: Run tests
        run: yarn test
